### ISSUE TITLE
Upgrade wgpu to 22.0

### ISSUE THREAD

**Issue by songhuaixu** [Swoorup/wgsl-bindgen#37]

**Comment by Swoorup** [comment]
Currently blocked by: https://github.com/bevyengine/naga_oil/pull/98

**Comment by 9SMTM6** [comment]
was fixed yesterday btw, IDK if you monitored these.

**Comment by Swoorup** [comment]
> was fixed yesterday btw, IDK if you monitored these.

Yup on top of it, I am waiting on the release. However won't be able to get to this until the next weekend, but can accept PRs until then. 

This should be quite straightforward compared to the last wgpu/naga_oil release though

**Comment by 9SMTM6** [comment]
BTW, the example doesn't compile on stable right now. It sets a feature in `include_absolute_path`, which also seems to be from you.

That blocked me from trying my hand at this earlier.

I'll just ignore the example and just run the tests in the actual crate.

**Comment by 9SMTM6** [comment]
puh. frankly, I'm out of my depth when it comes to upgrading this. With the first real error in `cargo check` I have no idea how to port this to the newer naga_oil function. That function removed a parameter (ShaderStages from naga), and I dont know where this information should go now. It was removed from the struct altogether. There is no changelist for naga_oil, and and I can't find any example code for how to port, since e.g. bevy-render, the one reverse-dependency out of the bevy project, did not update yet.

**Comment by Swoorup** [comment]
> BTW, the example doesn't compile on stable right now. It sets a feature in `include_absolute_path`, which also seems to be from you.
> 
> That blocked me from trying my hand at this earlier.
> 
> I'll just ignore the example and just run the tests in the actual crate.

You could use other output mode as someone mentioned here https://github.com/Swoorup/wgsl-bindgen/issues/32#issuecomment-2220768602, ie `UseComposerEmbed` to try using the stable compiler.

The `include_absolute_path` is used to embedded the shader path of the source, which is useful in implementing hotreloading shaders. The example enables all shader source output strategy. You could simply disable `UseComposerWithPath` option

**Comment by Swoorup** [comment]
Fixed in https://github.com/Swoorup/wgsl-bindgen/pull/40
Released: [0.15.0](https://crates.io/crates/wgsl_bindgen/0.15.0)
